"""
NOMBRE DE LOS ALUMNOS:
DULCE CECILIA HERNANDES DE LA CRUZ.
ERICK GABRIEL LOPEZ MELO.
LEONARDO LEDESMA MERCADO.
NOMBRE DEL DOCENTE:
ELI HUSIM RUIZ CRUZ.
GRUPO:
605
MATERIA:
ANALISIS DEL LENGUAJE NATURAL.
CARRERA:
CIENCIA DE DATOS E INTELIGENCIA ARTIFICIAL.
SEMESTRE:
6.TO
FECHA:
19/05/2025
ACTIVIDAD:
EL CODIGO DE LA CREACION DEL CODIGO QR DE DONDE SE ENCUENTRA UBICADO EL CUAL ES EN LA NUBE ENTONCES SOLO ANEXAREMOS LA DIRECCION DE DONDE
"""

import qrcode # IMPORTAMOS LA LIBRERIA "QRCODE" PARA QUE NOS FACILITE LA CREACION DE CODIGOS QR

# Crear un código QR
data = "https://docs.google.com/spreadsheets/d/1_eVIpi0ZVbQ4tZJ04ok618q3bnx_6x5q/edit?gid=640210769#gid=640210769" # AQUI DEFINIMOS EL CONTENIDO QUE LLEVARA EL CODIGO QR (UNA URL EN ESTE CASO)
qr = qrcode.make(data) # AQUI MANDAMOS LLAMAR LA VARIABLE "DATA" YA QUE ES LA QUE CONTENDRA EL CONTENIDO EL CUAL ES LA URL

# Guardar la imagen del QR
qr.save("codigo_qr.png") # AQUI SE GUARDA EL CODIGO QR GENERADO CON EL NOMBRE DE "CODIGO_QR.PNG"

print("Código QR generado y guardado como 'codigo_qr.png'") # AQUI LO SE QUE IMPRIME ES EL MENSAJE ENTRE COMILLAS PARA MENCIONAR QUE EL CODGIO QR FUE GENERADO CORRACTEMENTE GUARDADO EN NUESTRO ALMACENAMIENTO EXTERNO MOVIL EN EL CUAL ES "NUESTRA MEMORIA USB"